export const cardsData = [
  {
    id: 10,
    imgSrc: "/assets/images/udomi/3.jpg",
    dan: "12",
    mesec: "Apr",
    petName: "Cezar",
    pol: "Žensko",
    starost: "2 godine",
    vakcinisan: "vakcinisan",
    grad: "Pirot",
    kontakt: "0174758692",
    psp: "Očišćen od parazita / Obezbedjen prevoz",
    galery: [
      "/assets/images/udomi/4.jpg",
      "/assets/images/bobi_optimized.webp",
      "/assets/images/stari_optimized.webp",
      "/assets/images/macka02_optimized.webp",
    ],
    text1:
      "Cezar je vraćen i ponovo traži dom. Osoba koja ga je usvojila vratila ga je jer 'se ne slaže sa mačkama i pernatim životinjama'. Spasili smo ga sa ulice kada je imao svega mesec dana, sada ima oko 5 ipo meseci, vakcinisan je i očišćen od parazita, veseo i mazan. Ponovo tražimo dom za Cezara u kome će biti voljen, a što će on mnogostruko vratiti.",
    text2:
      "Bruno traži dom. Nađen je na Karaburmi kao štene, u lošem stanju. Da bi ga spasili od hladnoće uzeli smo ga kod nas, ali zbog posla u inostranstvu nismo u mogućnosti da ga zadržimo. Bruno ima 3 godine, velika je maza i dosta razigran. Ima pasoš, kastriran je, očišćen od parazita i redovno vakcinisan. Ako imate dvorište, za njega bi bilo idealno. Mogućnost prevoza u Srbiji.",
    text3: "Kontakt: +381 69 441 45 51, +381 60 351 45 80",
  },
  {
    id: 11,
    imgSrc: "/assets/images/udomi/5.jpg",
    dan: "12",
    mesec: "Apr",
    petName: "Mici",
    pol: "Žensko",
    starost: "2 godine",
    vakcinisan: "vakcinisan",
    grad: "Pirot",
    kontakt: "0174758692",
    psp: "Očišćen od parazita / Obezbedjen prevoz",
    galery: [
      "/assets/images/udomi/1.jpg",
      "/assets/images/bobi_optimized.webp",
      "/assets/images/stari_optimized.webp",
      "/assets/images/macka02_optimized.webp",
    ],
    text1:
      "Cezar je vraćen i ponovo traži dom. Osoba koja ga je usvojila vratila ga je jer 'se ne slaže sa mačkama i pernatim životinjama'. Spasili smo ga sa ulice kada je imao svega mesec dana, sada ima oko 5 ipo meseci, vakcinisan je i očišćen od parazita, veseo i mazan. Ponovo tražimo dom za Cezara u kome će biti voljen, a što će on mnogostruko vratiti.",
    text2:
      "Bruno traži dom. Nađen je na Karaburmi kao štene, u lošem stanju. Da bi ga spasili od hladnoće uzeli smo ga kod nas, ali zbog posla u inostranstvu nismo u mogućnosti da ga zadržimo. Bruno ima 3 godine, velika je maza i dosta razigran. Ima pasoš, kastriran je, očišćen od parazita i redovno vakcinisan. Ako imate dvorište, za njega bi bilo idealno. Mogućnost prevoza u Srbiji.",
    text3: "Kontakt: +381 69 441 45 51, +381 60 351 45 80",
  },
  {
    id: 12,
    imgSrc: "/assets/images/udomi/5.jpg",
    dan: "12",
    mesec: "Apr",
    petName: "Mici",
    pol: "Žensko",
    starost: "2 godine",
    vakcinisan: "vakcinisan",
    grad: "Pirot",
    kontakt: "0174758692",
    psp: "Očišćen od parazita / Obezbedjen prevoz",
    galery: [
      "/assets/images/udomi/1.jpg",
      "/assets/images/bobi_optimized.webp",
      "/assets/images/stari_optimized.webp",
      "/assets/images/macka02_optimized.webp",
    ],
    text1:
      "Cezar je vraćen i ponovo traži dom. Osoba koja ga je usvojila vratila ga je jer 'se ne slaže sa mačkama i pernatim životinjama'. Spasili smo ga sa ulice kada je imao svega mesec dana, sada ima oko 5 ipo meseci, vakcinisan je i očišćen od parazita, veseo i mazan. Ponovo tražimo dom za Cezara u kome će biti voljen, a što će on mnogostruko vratiti.",
    text2:
      "Bruno traži dom. Nađen je na Karaburmi kao štene, u lošem stanju. Da bi ga spasili od hladnoće uzeli smo ga kod nas, ali zbog posla u inostranstvu nismo u mogućnosti da ga zadržimo. Bruno ima 3 godine, velika je maza i dosta razigran. Ima pasoš, kastriran je, očišćen od parazita i redovno vakcinisan. Ako imate dvorište, za njega bi bilo idealno. Mogućnost prevoza u Srbiji.",
    text3: "Kontakt: +381 69 441 45 51, +381 60 351 45 80",
  },

  {
    id: 13,
    imgSrc: "/assets/images/udomi/1.jpg",
    dan: "12",
    mesec: "Apr",
    petName: "Mici",
    pol: "Žensko",
    starost: "2 godine",
    vakcinisan: "vakcinisan",
    grad: "Pirot",
    kontakt: "0174758692",
    psp: "Očišćen od parazita / Obezbedjen prevoz",
    galery: [
      "/assets/images/udomi/1.jpg",
      "/assets/images/bobi_optimized.webp",
      "/assets/images/stari_optimized.webp",
      "/assets/images/macka02_optimized.webp",
    ],
    text1:
      "Cezar je vraćen i ponovo traži dom. Osoba koja ga je usvojila vratila ga je jer 'se ne slaže sa mačkama i pernatim životinjama'. Spasili smo ga sa ulice kada je imao svega mesec dana, sada ima oko 5 ipo meseci, vakcinisan je i očišćen od parazita, veseo i mazan. Ponovo tražimo dom za Cezara u kome će biti voljen, a što će on mnogostruko vratiti.",
    text2:
      "Bruno traži dom. Nađen je na Karaburmi kao štene, u lošem stanju. Da bi ga spasili od hladnoće uzeli smo ga kod nas, ali zbog posla u inostranstvu nismo u mogućnosti da ga zadržimo. Bruno ima 3 godine, velika je maza i dosta razigran. Ima pasoš, kastriran je, očišćen od parazita i redovno vakcinisan. Ako imate dvorište, za njega bi bilo idealno. Mogućnost prevoza u Srbiji.",
    text3: "Kontakt: +381 69 441 45 51, +381 60 351 45 80",
  },
  {
    id: 14,
    imgSrc: "/assets/images/udomi/2.jpg",
    dan: "12",
    mesec: "Apr",
    petName: "Mici",
    pol: "Žensko",
    starost: "2 godine",
    vakcinisan: "vakcinisan",
    grad: "Pirot",
    kontakt: "0174758692",
    psp: "Očišćen od parazita / Obezbedjen prevoz",
    galery: [
      "/assets/images/udomi/1.jpg",
      "/assets/images/bobi_optimized.webp",
      "/assets/images/stari_optimized.webp",
      "/assets/images/macka02_optimized.webp",
    ],
    text1:
      "Cezar je vraćen i ponovo traži dom. Osoba koja ga je usvojila vratila ga je jer 'se ne slaže sa mačkama i pernatim životinjama'. Spasili smo ga sa ulice kada je imao svega mesec dana, sada ima oko 5 ipo meseci, vakcinisan je i očišćen od parazita, veseo i mazan. Ponovo tražimo dom za Cezara u kome će biti voljen, a što će on mnogostruko vratiti.",
    text2:
      "Bruno traži dom. Nađen je na Karaburmi kao štene, u lošem stanju. Da bi ga spasili od hladnoće uzeli smo ga kod nas, ali zbog posla u inostranstvu nismo u mogućnosti da ga zadržimo. Bruno ima 3 godine, velika je maza i dosta razigran. Ima pasoš, kastriran je, očišćen od parazita i redovno vakcinisan. Ako imate dvorište, za njega bi bilo idealno. Mogućnost prevoza u Srbiji.",
    text3: "Kontakt: +381 69 441 45 51, +381 60 351 45 80",
  },
  {
    id: 15,
    imgSrc: "/assets/images/udomi/3.jpg",
    dan: "12",
    mesec: "Apr",
    petName: "Mici",
    pol: "Žensko",
    starost: "2 godine",
    vakcinisan: "vakcinisan",
    grad: "Pirot",
    kontakt: "0174758692",
    psp: "Očišćen od parazita / Obezbedjen prevoz",
    galery: [
      "/assets/images/udomi/1.jpg",
      "/assets/images/bobi_optimized.webp",
      "/assets/images/stari_optimized.webp",
      "/assets/images/macka02_optimized.webp",
    ],
    text1:
      "Cezar je vraćen i ponovo traži dom. Osoba koja ga je usvojila vratila ga je jer 'se ne slaže sa mačkama i pernatim životinjama'. Spasili smo ga sa ulice kada je imao svega mesec dana, sada ima oko 5 ipo meseci, vakcinisan je i očišćen od parazita, veseo i mazan. Ponovo tražimo dom za Cezara u kome će biti voljen, a što će on mnogostruko vratiti.",
    text2:
      "Bruno traži dom. Nađen je na Karaburmi kao štene, u lošem stanju. Da bi ga spasili od hladnoće uzeli smo ga kod nas, ali zbog posla u inostranstvu nismo u mogućnosti da ga zadržimo. Bruno ima 3 godine, velika je maza i dosta razigran. Ima pasoš, kastriran je, očišćen od parazita i redovno vakcinisan. Ako imate dvorište, za njega bi bilo idealno. Mogućnost prevoza u Srbiji.",
    text3: "Kontakt: +381 69 441 45 51, +381 60 351 45 80",
  },
  {
    id: 16,
    imgSrc: "/assets/images/udomi/4.jpg",
    dan: "12",
    mesec: "Apr",
    petName: "Mici",
    pol: "Žensko",
    starost: "2 godine",
    vakcinisan: "vakcinisan",
    grad: "Pirot",
    kontakt: "0174758692",
    psp: "Očišćen od parazita / Obezbedjen prevoz",
    galery: [
      "/assets/images/udomi/1.jpg",
      "/assets/images/bobi_optimized.webp",
      "/assets/images/stari_optimized.webp",
      "/assets/images/macka02_optimized.webp",
    ],
    text1:
      "Cezar je vraćen i ponovo traži dom. Osoba koja ga je usvojila vratila ga je jer 'se ne slaže sa mačkama i pernatim životinjama'. Spasili smo ga sa ulice kada je imao svega mesec dana, sada ima oko 5 ipo meseci, vakcinisan je i očišćen od parazita, veseo i mazan. Ponovo tražimo dom za Cezara u kome će biti voljen, a što će on mnogostruko vratiti.",
    text2:
      "Bruno traži dom. Nađen je na Karaburmi kao štene, u lošem stanju. Da bi ga spasili od hladnoće uzeli smo ga kod nas, ali zbog posla u inostranstvu nismo u mogućnosti da ga zadržimo. Bruno ima 3 godine, velika je maza i dosta razigran. Ima pasoš, kastriran je, očišćen od parazita i redovno vakcinisan. Ako imate dvorište, za njega bi bilo idealno. Mogućnost prevoza u Srbiji.",
    text3: "Kontakt: +381 69 441 45 51, +381 60 351 45 80",
  },

  {
    id: 17,
    imgSrc: "/assets/images/udomi/5.jpg",
    dan: "12",
    mesec: "Apr",
    petName: "Cezar",
    pol: "Žensko",
    starost: "2 godine",
    vakcinisan: "vakcinisan",
    grad: "Beograd",
    kontakt: "0174758692",
    psp: "Očišćen od parazita / Obezbedjen prevoz",
    galery: [
      "/assets/images/udomi/1.jpg",
      "/assets/images/bobi_optimized.webp",
      "/assets/images/stari_optimized.webp",
      "/assets/images/macka02_optimized.webp",
    ],
    text1:
      "Cezar je vraćen i ponovo traži dom. Osoba koja ga je usvojila vratila ga je jer 'se ne slaže sa mačkama i pernatim životinjama'. Spasili smo ga sa ulice kada je imao svega mesec dana, sada ima oko 5 ipo meseci, vakcinisan je i očišćen od parazita, veseo i mazan. Ponovo tražimo dom za Cezara u kome će biti voljen, a što će on mnogostruko vratiti.",
    text2:
      "Bruno traži dom. Nađen je na Karaburmi kao štene, u lošem stanju. Da bi ga spasili od hladnoće uzeli smo ga kod nas, ali zbog posla u inostranstvu nismo u mogućnosti da ga zadržimo. Bruno ima 3 godine, velika je maza i dosta razigran. Ima pasoš, kastriran je, očišćen od parazita i redovno vakcinisan. Ako imate dvorište, za njega bi bilo idealno. Mogućnost prevoza u Srbiji.",
    text3: "Kontakt: +381 69 441 45 51, +381 60 351 45 80",
  },
  {
    id: 18,
    imgSrc: "/assets/images/udomi/6.jpg",
    dan: "12",
    mesec: "Apr",
    petName: "Mačići",
    pol: "Žensko",
    starost: "2 godine",
    vakcinisan: "vakcinisan",
    grad: "Pirot",
    kontakt: "0174758692",
    psp: "Očišćen od parazita / Obezbedjen prevoz",
    galery: [
      "/assets/images/udomi/1.jpg",
      "/assets/images/bobi_optimized.webp",
      "/assets/images/stari_optimized.webp",
      "/assets/images/macka02_optimized.webp",
    ],
    text1:
      "Cezar je vraćen i ponovo traži dom. Osoba koja ga je usvojila vratila ga je jer 'se ne slaže sa mačkama i pernatim životinjama'. Spasili smo ga sa ulice kada je imao svega mesec dana, sada ima oko 5 ipo meseci, vakcinisan je i očišćen od parazita, veseo i mazan. Ponovo tražimo dom za Cezara u kome će biti voljen, a što će on mnogostruko vratiti.",
    text2:
      "Bruno traži dom. Nađen je na Karaburmi kao štene, u lošem stanju. Da bi ga spasili od hladnoće uzeli smo ga kod nas, ali zbog posla u inostranstvu nismo u mogućnosti da ga zadržimo. Bruno ima 3 godine, velika je maza i dosta razigran. Ima pasoš, kastriran je, očišćen od parazita i redovno vakcinisan. Ako imate dvorište, za njega bi bilo idealno. Mogućnost prevoza u Srbiji.",
    text3: "Kontakt: +381 69 441 45 51, +381 60 351 45 80",
  },
  {
    id: 19,
    imgSrc: "/assets/images/bobi_optimized.webp",
    dan: "07",
    mesec: "Mar",
    petName: "Lila",
    pol: "Žensko",
    starost: "2 godine",
    vakcinisan: "vakcinisan",
    grad: "Leskovac",
    kontakt: "0171234567",
    psp: "Očišćen od parazita / Sterilisan / Prevoz",
    galery: [
      "/assets/images/udomi/udomime.jpg",
      "/assets/images/udomi/udomime.jpg",
      "/assets/images/udomi/udomime.jpg",
      "/assets/images/udomi/udomime.jpg",
    ],
    text1:
      "Cezar je vraćen i ponovo traži dom. Osoba koja ga je usvojila vratila ga je jer 'se ne slaže sa mačkama i pernatim životinjama'. Spasili smo ga sa ulice kada je imao svega mesec dana, sada ima oko 5 ipo meseci, vakcinisan je i očišćen od parazita, veseo i mazan. Ponovo tražimo dom za Cezara u kome će biti voljen, a što će on mnogostruko vratiti.",
    text2:
      "Bruno traži dom. Nađen je na Karaburmi kao štene, u lošem stanju. Da bi ga spasili od hladnoće uzeli smo ga kod nas, ali zbog posla u inostranstvu nismo u mogućnosti da ga zadržimo. Bruno ima 3 godine, velika je maza i dosta razigran. Ima pasoš, kastriran je, očišćen od parazita i redovno vakcinisan. Ako imate dvorište, za njega bi bilo idealno. Mogućnost prevoza u Srbiji.",
    text3: "Kontakt: +381 69 441 45 51, +381 60 351 45 80",
  },
];
