export const blogList = [
  {
    id: 1,
    title: 'Štene psa',
    category: ['Zdravlje', ' /', ' Higijena', ' /', ' Dresura'],
    subCategory: ['Štene'],
    description:
      "Štene psa je mladi pas koji se obično rađa slep i nem, te zavisi od majke za hranu i brigu. Kada štene navrši oko tri nedelje starosti, počinje se hraniti i piti vodu, a majka ih postepeno prestaje dojiti. Važno je osigurati sigurno okruženje za štene i ukloniti sve potencijalne opasnosti, poput toksičnih stvari i predmeta koji bi ih mogli povrediti. Nega štenaca: Štenci pasa zahtevaju puno pažnje i nege. Kada ih donesete kući, biće im potreban prilagođen raspored ishrane, spavanja i vežbanja. Osim toga, morate se pobrinuti za pravilno čišćenje, kupanje i negu dlake. Dresura štenaca: Dresura je od suštinskog značaja za štence pasa. Potrebno je da nauče osnovne komande, kao što su sedi, lezi, ostani i dodji. Pored osnovnih komandi, takođe je važno da nauče i socijalizaciju. Štenci pasa trebaju pravilnu ishranu kako bi rasli i razvijali se zdravo. Zdravlje štenaca: Slično kao i kod ljudi, štenad se mogu razboleti i obolelosti su često ozbiljnije kod njih nego kod odraslih pasa. Razlike između rasa štenaca: Postoji veliki broj različitih rasa pasa i svaka od njih ima svoje specifičnosti i osobine. Kako odabrati pravo štene za vas: Kada donosite odluku o kupovini ili usvajanju šteneta, važno je izabrati pravog psa za vaš stil života i porodicu. Veze između ljudi i štenaca su nešto što je za mnoge vlasnike pasa veoma važno. Psi su poznati kao čovekov najbolji prijatelj, i za mnoge ljude su oni mnogo više od običnih kućnih ljubimaca. Štenci su puni energije i ljubavi, te mogu biti izvrsni ljubimci i pratioci uz odgovarajuću brigu, trening i ljubav.",
    createdAt: 'Feb 06, 2023',
    cover: '/assets/images/mladi.png'
  },
  {
    id: 8,
    title: 'Mladi psi',
    category: ['Zdravlje', ' /', ' Higijena'],
    subCategory: ['Zdravlje', 'Higijena'],
    description:
      "Ishrana: Mladi psi imaju specifične nutritivne potrebe koje se razlikuju od potreba odraslih pasa. Važno je pronaći pravu hranu koja će zadovoljiti potrebe vašeg psa u njegovim ranim godinama života. Vakcinacija i preventivna medicina: Mladi psi su posebno podložni različitim bolestima i infekcijama, tako da je važno da se redovno vakcinišu i dobiju preventivne tretmane protiv buva, krpelja i drugih parazita. Važno je hraniti mlade pse uravnoteženom i kvalitetnom hranom, bilo suvom hranom ili konzervom, u skladu s preporukama veterinaru i specifičnim nutritivnim potrebama svake rase. Vežba i aktivnosti: Mladi psi su često vrlo aktivni i energični, tako da im je potrebna dovoljna količina fizičke aktivnosti i vežbe. Šetnje, trčanje, igre i druge aktivnosti koje su prilagođene dobi, veličini i rasi psa, važne su za razvoj zdravog tela i uma u mladih pasa. Higijena: Održavanje higijene vašeg psa je ključno za njegovo zdravlje i dobrobit. To uključuje redovno kupanje, čišćenje zubi, održavanje čistim ušiju i očiju, kao i održavanje dlake čistom. Rano otkrivanje i liječenje bolesti: Mladi psi su podložni različitim zdravstvenim problemima i bolestima, tako da je važno da naučite prepoznati simptome bolesti i da vaš pas dobije pravilnu dijagnozu i lečenje na vreme. Kada je riječ o higijeni, trebate se usredotočiti ne samo na čistoću vašeg psa, već i na okolinu u kojoj živi. To uključuje redovno čišćenje posuda za hranu i vodu, igračaka i kreveta vašeg psa, kao i uspostavljanje sigurnog i higijenskog okruženja za vašeg psa. Takođe, ne zaboravite na važnost socijalizacije i obuke vašeg mladog psa kako bi postao uravnotežen i discipliniran odrasli pas. Mladi psi su podložni različitim zdravstvenim problemima, poput zaraznih bolesti, problema s probavom, kožnim infekcijama i drugim, pa je važno redovito posećivati veterinara radi prevencije i lečenja tih problema.",
    createdAt: 'June 03, 2021',
    cover: '/assets/images/bobi.png',
  },
  {
    id: 4,
    title: 'Mali psi',
    category: ['Putovanja', ' /', ' avanture'],
    subCategory: ['Putovanja', 'Avanture'],
    description:
      "Putovanja sa malim psima mogu biti zabavna i uzbudljiva avantura za vas i vašeg ljubimca, ali zahtevaju određenu pripremu kako bi se osiguralo da putovanje bude sigurno i ugodno za vašeg psa. Pre nego što krenete na put, proverite jesu li svi vaši dokumenti u redu, uključujući pasoš i potrebne dokumente za vašeg psa, ako putujete u inostranstvo. Takođe, proverite jesu li vaši kontakt podaci ažurni u mikročipu vašeg psa. Kada se pripremate za put, važno je razmotriti kako ćete putovati. Ako putujete automobilom, razmislite o kupovini sigurnosnog pojasa ili transporter za psa. Ako putujete avionom, proverite uslove prevoza za ljubimce i kako se vaš pas može putovati u kabini ili teretnom delu aviona. Kada stignete na odredište, važno je osigurati da vaš pas bude ugodno i sigurno smešten. Odaberite smeštaj u kojem su psi dobrodošli i unapred proverite jesu li sve potrebne pogodnosti dostupne, kao što su otvoreni prostori za šetnju i prostor za druženje s vašim ljubimcem. Ako putujete u stranu zemlju, proverite trebate li neke dodatne papire i dokumente za svog psa. Tokom putovanja, važno je osigurati da vaš pas bude udoban i da ima dovoljno vode i hrane. Budite spremni za zaustavljanje na redovitim intervalima kako bi vaš pas mogao prošetati, istegnuti noge i obaviti nuždu. Putovanje s vašim malim psom može biti izazovno, ali uz dobru pripremu i planiranje, može biti i vrlo ugodno iskustvo za vas i vašeg ljubimca. Budite otvoreni za nove avanture i uživajte u putovanju sa svojim malim psom. Drugo važno područje za putovanja i avanture s malim psima je istraživanje okoline i aktivnosti koje mogu uživati s vama. Ako ste na odmoru u prirodi, šetnje u prirodi mogu biti odlična aktivnost za vas i vašeg psa. Obavezno proverite uslove šetnje i uslove za pse na tom području i ponesite dovoljno vode i hrane za vas i vašeg psa. Ako ste više avanturistički nastrojeni, možda biste hteli pokušati s nekom od ekstremnih aktivnosti s vašim psom, poput vožnje kajaka, paddleboardinga ili planinarenja. Pre nego što se upustite u bilo koju od ovih aktivnosti, proverite jesu li sigurne za vašeg psa i jesu li prikladne za njegovu veličinu i sposobnosti. Ako ste na odmoru u gradu, proverite jesu li psima dozvoljeni određeni prostori i zgrade, kao što su parkovi i javni prijevoz. Neki gradovi imaju posebne parkove za pse, gde vaš pas može trčati, igrati se i socijalizovati sa drugim psima. ",
    createdAt: 'Dec 23, 2022',
    cover: '/assets/images/oto.png'
  },
  
  {
    id: 2,
    title: 'Psi srednje građe',
    category: ['Zabava', ' /', ' Kultura'],
    subCategory: ['Srednji psi'],
    description:
      "Važno je imati na umu da neki psi srednje veličine mogu biti vrlo energični, dok drugi mogu biti manje aktivni. Stoga, odabir aktivnosti za vašeg srednjeg psa trebao bi uzeti u obzir njegovu gradju i osobine. Aktivnosti na otvorenom: Srednji psi često vole trčati i igrati se na otvorenom. Šetnje, trčanje po parku, bacanje loptice i igra sa drugim psima mogu pružiti puno zabave i vežbe za vašeg psa. Uz trening i socijalizaciju, psi srednje građe mogu uživati u aktivnostima poput poslušnosti, agilnosti i lovačkih aktivnosti, koje poboljšavaju njihove veštine i pružaju im mentalni izazov. Mogu biti izvrsni pratitelji na izletima i avanturama poput planinarenja, kampovanja i ribolova, a uz odgovarajuću obuku i opremu, mogu se prilagoditi različitim situacijama. Trikovi i igre: Srednji psi su često vrlo inteligentni i mogu brzo naučiti nove trikove. Učenje novih trikova i igara poput traženja skrivenih predmeta, može biti zabavno i stimulativno za vašeg psa. Društvene aktivnosti: Psi su društvena bića i vole biti deo porodice i zajednice. Razne društvene aktivnosti poput posete psima u azilima, druženja s drugim psima, pa čak i učestvovanje na događajima poput izložbi pasa, mogu pružiti zanimljive i uzbudljive iskustva vašem srednjem psu. Zabava u zatvorenom prostoru: Za kišne ili hladne dane, možete organizovati zabavne aktivnosti u zatvorenom prostoru za svog psa. To može uključivati igranje skrivača, trening ili učenje novih trikova, ili čak gledanje televizije zajedno. Umetnost i kultura: Psi mogu uživati u umetnosti i kulturi na svoj način. Posete izložbama umetnosti, muzejima ili kazalištima koji su prijateljski raspoloženi prema psima, mogu biti zanimljivi i stimulativni za vašeg srednjeg psa.",
    createdAt: 'Jan 03, 2023',
    cover: '/assets/images/srednji.png',
  },
  {
    id: 3,
    title: 'Veliki psi',
    category: ['Trening', ' /', ' Ponašanje'],
    subCategory: ['Veliki psi'],
    description:
      "Veliki psi su inteligentni, živahni i vrlo društveni, što ih čini savršenim kandidatima za trening i socijalizaciju. Evo nekoliko saveta za trening i ponašanje za velike pse: Počnite rano: Vrlo je važno početi s treningom i socijalizacijom velikih pasa što je pre moguće. Ovo se posebno odnosi na pse koje su po prirodi dominantni i teže ih je kontrolirati. Što se ranije počne s treningom, to će biti lakše izgraditi temelje za dobro ponašanje u budućnosti. Učite osnovne naredbe: Naučite svog psa osnovne naredbe poput sedi, dođi, stani, ostani i hodaj pored. Ove naredbe su vrlo važne za upravljanje vašim psom i kontrolisanje njegovog ponašanja. Socijalizirajte svog psa: Socijalizacija je ključna za razvoj samopouzdanja i dobrog ponašanja vašeg psa. Učinite sve što je potrebno kako bi vaš pas bio izložen što više ljudi, životinja i okoline. To će pomoći vašem psu da razvije samopouzdanje i postane opušteniji u različitim situacijama. Budite dosledni: Važno je biti dosledan u treningu i disciplini vašeg psa. Vaš pas će biti zbunjen ako mu dopustite da radi jednu stvar danas, a drugu sutra. Budite dosledni u svom pristupu i uvek sledite isti postupak. Nagradite dobro ponašanje: Nagrada je jedan od najboljih načina za podsticanje dobrog ponašanja kod vašeg psa. Bilo da se radi o pohvalama, maženjem ili poslasticama, nagrada će vašem psu pomoći da shvati da je dobro ponašanje povezano s pozitivnim iskustvima. Budite strpljivi: Trening psa može biti dug i naporan proces, posebno kod velikih pasa koji mogu biti tvrdoglavi. Budite strpljivi s vašim psom i ne očekujte da se sve odmah dogodi. Redovito vežbajte i s vremenom ćete videti poboljšanja u ponašanju vašeg psa. Tražite pomoć stručnjaka: Ako se borite s treningom i ponašanjem svog psa, nemojte se bojati zatražiti pomoć stručnjaka. Veterinari, treneri pasa i drugi stručnjaci mogu vam pomoći u razvoju plana treninga i rešavanju poteškoća. Vežbajte redovno: Redovna telesna aktivnost ključna je za dobro zdravlje i ponašanje vašeg psa. Veliki psi trebaju dosta vežbe kako bi ostali zdravi i sretni. Redovne šetnje, trčanje, plivanje i igranje su odlični načini da vaš pas dobije fizičku i mentalnu stimulaciju. Održavajte rutinu: Veliki psi vole rutinu i navikavaju se na nju. Pokušajte održati rutinu u svakodnevnom životu vašeg psa, uključujući hranjenje, vežbanje, spavanje i druženje sa porodicom. Ovo će pomoći vašem psu da se oseća sigurno i ugodno u svom okruženju.",
    createdAt: 'Feb 01, 2023',
    cover: '/assets/images/nemacki.png'
  },
  {
    id: 6,
    title: 'Stari psi',
    category: ['Ishrana', ' /', ' Higijena', ' /', ' Zdravlje'],
    subCategory: ['Stari', 'Psi'],
    description:
      "Posećujte veterinara redovito: Redovni pregledi su ključni za otkrivanje zdravstvenih problema u ranim fazama. To je veoma važno kod starijih pasa koji su podložniji bolestima. Veterinar može preporučiti testove krvi, pregled zuba i desni, pregled srca i drugih organa, te dati preporuke za prilagođavanje ishrane i nege vašeg psa. Prilagodite ishranu: Stariji psi imaju smanjenu aktivnost i sporiji metabolizam, pa im je potrebno manje hrane nego pre. Takođe, stariji psi mogu imati problema s probavom i apetitom, pa se prehrana može prilagoditi u skladu s tim. Veterinar može preporučiti posebnu prehranu za starije pse. Pobrinite se za oralnu higijenu: Stariji psi su skloniji zubnom kamencu i infekcijama desni, što može dovesti do lošeg daha, gubitka zuba i ozbiljnijih zdravstvenih problema. Redovito četkanje zubi i posete veterinaru za čišćenje zubi i desni mogu pomoći u održavanju oralne higijene. Osigurajte dovoljno vežbe: Iako stariji psi ne mogu izdržati naporne aktivnosti kao pre, i dalje im treba redovna telesna aktivnost kako bi ostali zdravi. Šetnje i plivanje su odlični načini za vežbanje starijeg psa, ali uvek proverite s veterinarom kakve su granice vašeg psa. Pazite na znakove starenja: Stariji psi mogu imati različite zdravstvene probleme koji se mogu pojaviti s godinama, kao što su smanjena pokretljivost, gubitak sluha ili vida, bol u zglobovima i slično. Ako primetite bilo kakve promene u ponašanju ili zdravlju svog psa, posetite veterinara. Stariji psi su vredan deo porodice i zaslužuju posebnu pažnju i brigu kako bi ostali zdravi i sretni u svojim godinama. Redovne posete veterinaru, prilagođena ishrana, briga o oralnoj higijeni, dovoljno vežbe i praćenje znakova starenja mogu pomoći u održavanju zdravlja vašeg starijeg psa i produžiti mu život. Uz to, stariji psi takođe mogu zahtevati prilagođavanje u svom okruženju. Na primer, možda će trebati mekše i udobnije mesto za spavanje ili lakši pristup hrani i vodi zbog smanjene pokretljivosti. Konačno, pružanje ljubavi, pažnje i emocionalne podrške svom starijem psu može biti jednako važno kao i briga o njihovom zdravlju i higijeni, te može pomoći u održavanju njihovog zdravog i sretnog starenja.",
    createdAt: 'Feb 04, 2023',
    cover: '/assets/images/stari.png',
  },
  {
    id: 5,
    title: 'Štene mačke',
    category: 'Razno',
    subCategory: ['Mačke', 'Zdravlje', 'Štenci'],
    description:
      "Štene mačke do 6 meseci zahtevaju posebnu opreznost kada je u pitanju zdravlje, ishrana i higijena. Njihov imuni sistem je još uvek slab i nisu u potpunosti razvijeni, zato su osetljiviji na bolesti i infekcije. Jedna od najvažnijih stvari za zdravlje šteneta mačke je osigurati mu pravilnu ishranu. Kvalitetna hrana koja sadrži sve hranjive stvari koje mačka treba, poput proteina, vitamina i minerala, ključna je za rast i razvoj zdravog šteneta. Također je važno paziti da hrana ne sadrži sastojke na koje bi mačka mogla biti alergična. Higijena je takođe važan aspekt brige o štenetu mačke. Štene bi trebalo redovito četkati, a posebno ako je reč o dugodlakoj mački, kako bi se sprečilo zapetljavanje dlake. Takođe, važno je održavati čistoću mačje prostorije i održavati higijenu mačjeg ormarića i posuda za hranu i vodu. Redovni veterinarski pregledi su takođe ključni za zdravlje šteneta mačke. Veterinar će proveriti njeno zdravstveno stanje i pružiti savete o daljim koracima. Konačno, važno je obratiti pažnju na ponašanje šteneta mačke i osigurati mu dovoljno vremena za igru i druženje. Mačke su po prirodi znatiželjne i igračke mogu pomoći u razvoju njihovih motoričkih sposobnosti i društvenih veština. Uz pravilnu ishranu, higijenu, veterinarske preglede i društvenu interakciju, štene mačke može rasti u zdravu, sretnu odraslu mačku koja će biti ljubavni i odan kućni ljubimac. Jedan od najvažnijih elemenata u prehrani šteneta mačke je pravilna hidratacija. Mačke su po prirodi manje žedne i imaju tendenciju da piju manje vode od drugih životinja. Kako bi se osiguralo da štene mačke ima dovoljno tečnosti, preporučuje se redovno menjanje vode u posudi za piće ili, ako je potrebno, korištenje fontane za piće. Kada je u pitanju zdravlje šteneta mačke, važno je paziti na znakove bilo kakvih zdravstvenih problema, poput proliva, povraćanja ili gubitka apetita. Ako primetite bilo kakve neobične simptome, obratite se svom veterinaru odmah. Uz puno ljubavi, pažnje i brige, štene može postati neverovatan dodatak vašem domu. Pripazite na njegovu ishranu, higijenu i zdravlje, i sledite savete svog veterinara kako biste osigurali da vaše štene mačke raste u sretnu, zdravu i dobro prilagođenu mačku.",
    createdAt: 'Feb 03, 2022',
    cover: '/assets/images/macke.png'
  },
  
  
  {
    id: 7,
    title: 'Svet mačke',
    category: ['Svet', ' /', ' Mačke'],
    subCategory: ['Mačke', 'Razno'],
    description:
      "10 stvari koje vaša mačka ne voli, a vi toga možda niste ni svesni: Grubo rukovanje: Mačke ne vole grubo rukovanje, a pogotovo ne vole kada ih hvatate za rep ili za šape. Glasni zvukovi: Mačke imaju veoma osetljiv sluh, pa glasni zvukovi mogu biti zastrašujući za njih. Pokušajte da izbegavate jaku muziku, viku i druge bučne zvukove. Nedostatak privatnosti: Mačke vole da imaju svoj prostor i vreme za sebe. Ako im stalno smetate ili ih ne ostavljate same kada to žele, mogu postati frustrirane. Mirisi: Mačke imaju izuzetno razvijen njuh, pa neke mirise ne podnose. Npr. citrusi su jako neugodni za njih. Promene u ishrani: Mačke su naviknute na svoju hranu, pa promena u ishrani može biti stresna za njih. Uvek treba postepeno uvoditi novu hranu u njihovu ishranu. Nasilni kućni ljubimci: Mačke su plašljive životinje i ne vole kada ih drugi kućni ljubimci progone ili napadaju. Nedostatak igre: Mačke su vrlo aktivne životinje i treba im omogućiti da se igraju i istražuju svoje okruženje. Previše maženja: Iako mnoge mačke vole maženje, previše maženja ih može uznemiriti i iziritirati. Nečista okolina: Mačke su vrlo čiste životinje i ne vole prljavštinu i nered. Redovno čišćenje njihove okoline je neophodno. Ignorisanje: Mačke vole da imaju pažnju i ne vole kada se ignorišu. Uvek pokušajte da izdvojite vreme za mačku i da joj pružite dovoljno pažnje. Svet mačaka prepun je neverojatnih činjenica, od toga kako vide svet do toga kako se ponašaju u prema svojim vlasnicima. Mačke takođe imaju važnu ulogu u ljudskoj kulturi, od drevnih civilizacija koje su ih smatrale svetim životinjama do moderne popularne kulture koja ih slavi kao simbol elegancije, tajanstvenosti i samostalnosti.",
    createdAt: 'Jan 07, 2023',
    cover: '/assets/images/macka02.png',
  },
  {
    id: 9,
    title: 'Zašto su mačke fascinantne?',
    category: 'Zanimljivosti',
    subCategory: ['Mačke', 'Razno'],
    description:
      "5 neverovatnih činjenica o mačkama, u nastavku se nalaze neke od najzanimljivijih činjenica o mačkama: Sposobnost prilagođavanja: Mačke su neverovatno prilagodljive životinje. One se mogu prilagoditi različitim uslovima i okolinama, iako su vrlo osetljive na promene u rutini i navikama. Takođe, one su vrlo prilagodljive u vezi sa ishranom i mogu preživjeti na različitim vrstama hrane. Neobičan metabolizam: Mačke imaju drugačiji metabolizam u poređenju sa drugim životinjama. One su mesojedi, što znači da trebaju proteine ​​kako bi opstale. Takođe, mačke ne mogu samostalno svariti neke esencijalne aminokiseline, poput taurina, što znači da moraju dobiti ove hranjive sastojke iz hrane. Zapanjujuća ravnoteža: Mačke su poznate po svojoj neverovatnoj ravnoteži. One su u stanju da ostanu u ravnoteži čak i na uskim i neugodnim površinama, poput žice ili uskog zida. Ovo je zato što imaju neverovatne sposobnosti ravnoteže koje su razvile kroz godine evolucije kako bi se snašle u svom prirodnom okruženju. Oštri zubi i kandže: Mačke imaju oštre zube i kandže koje koriste za lov i odbranu. Njihove kandže su uvučene dok ne budu potrebne, što omogućava da izbegnu nepotrebni trošak energije. One takođe mogu lako povući svoje kandže unazad kada ih ne koriste, što im omogućava da ih zaštite i održe ih oštrim. Senzorički organi: Mačke imaju vrlo osetljive senzoričke organe. One imaju odličan sluh, vid i njuh, što im omogućava da budu vrlo dobri lovci. Takođe imaju izuzetno osetljiv dodir i sposobnost da osete vibracije, što im pomaže da se snalaze u mraku i da se brzo prilagode novim situacijama.",
    createdAt: 'June 03, 2022',
    cover: '/assets/images/higijenaMacke.png',
  }
  
];
